#!/usr/bin/env bash
# displays:
#   -the content of the file /etc/passwd
#   -username
#   -user id
#   -Home directory path for the user
txt="/etc/passwd"
while read -r l
do
    echo "$l" | cut -d ':' -f 1,3,6
done < $txt
