#!/usr/bin/env bash
# displays:
#   -the content of the file /etc/passwd, using the while loop + IFS
#   Format: The user USERNAME is part of the GROUP_ID gang, lives in
#           HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by
#           the passcode PASSWORD, more info about the user here: USER ID INFO
txt="/etc/passwd"
while read -r l
do
    user=$(echo "$l" | cut -d ':' -f 1)
    group_id=$(echo "$l" | cut -d ':' -f 4)
    home_dir=$(echo "$l" | cut -d ':' -f 6)
    command=$(echo "$l" | cut -d ':' -f 7)
    user_id=$(echo "$l" | cut -d ':' -f 3)
    pass=$(echo "$l" | cut -d ':' -f 2)
    user_id_info=$(echo "$l" | cut -d ':' -f 5)
    echo "The user $user is part of the $group_id gang, lives in $home_dir and rides $command. $user_id's place is protected by the passcode $pass, more info about the user here: $user_id_info"
done < $txt
